carometro/photos/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('clear/', views.clear_database, name='clear_database'),
    path('list-photos/', views.list_photos, name='list_photos'),
    path('progress-bar-upload/', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'),
]

carometro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.static import serve




urlpatterns = [
    path('media/', serve,{'document_root': settings.MEDIA_ROOT}),
    path('static/', serve,{'document_root': settings.STATIC_ROOT}),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('photos/', include(('carometro.photos.urls','photos'), namespace='photos')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carometro/photos/models.py
from __future__ import unicode_literals

from django.db import models


class Photo(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/', blank=True)

carometro/photos/forms.py
from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file', )

carometro/photos/views.py
import time

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View

from .forms import PhotoForm
from .models import Photo


class ProgressBarUploadView(View):
    def get(self, request):
        photos_list = Photo.objects.all()
        return render(self.request, 'photos/progress_bar_upload/progress.html', {'photos': photos_list})

    def post(self, request):
        form = PhotoForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.title = photo.file.name
            photo.image = photo.file
            photo = form.save()
            data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url, 'title': photo.file.name}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def clear_database(request):
    for photo in Photo.objects.all():
        photo.file.delete()
        photo.delete()
    return redirect(request.POST.get('next'))

def list_photos(request):
    photos_list = Photo.objects.all()
    return render(request, 'photos/listing_photos/list.html', {'photos': photos_list})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Copião para Estudios Fotograficos{% endblock %}</title>
</head>

<body>
<div class="container-fluid">

    <nav class="navbar navbar-expand-md navbar-light bg-light">

        <a class="navbar-brand" href="#">Face-o-Matic</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSite">

            <ul class="navbar-nav ml-auto">

                <li class="navbar-item">
                    <a class="nav-link" href="#">Inicio</a>
                </li>

                  <li class="navbar-item">
                    <a class="nav-link" href="{% url 'photos:list_photos' %}">Visualizar</a>
                </li>

                  <li class="navbar-item">
                    <a class="nav-link" href="{% url 'photos:progress_bar_upload' %}">Upload</a>
                </li>

                <li class="navbar-item">
                    <a class="nav-link" href="#">Contato</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="http://www.ricardoportela.com.br">ricardoportela.com.br</a>
                </li>
            </ul>

        </div>

    </nav>
</div>

<div class="container-fluid">

    {% block content %}
      {% endblock %}


</div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'photos/js/basic-upload.js' %}"></script>
{% endblock %}

</body>
</html>

templates/clear_database.html
<div style="margin-bottom: 20px;">
  <button type="button" class="btn btn-primary js-upload-photos">
    <span class="glyphicon glyphicon-cloud-upload"></span> Gerar PDF
  </button>
  <input id="fileupload" type="file" name="file" multiple style="display: none;" data-url="{% url 'photos:progress_bar_upload' %}"
    data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
</div>

  <form method="post" action="{% url 'photos:clear_database' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger pull-right">
      <span class="glyphicon glyphicon-trash"></span> Clear Database
    </button>
  </form>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="page-header">Visualizador de Fotos (Carometro/Copião)</h1>
  <p class="lead">Clique no link carregamento para upload das fotos.</p>
  <hr>

{% endblock %}

templates/photos/listing_photos/list.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
<!--{% block title %}Matriz de Impressão{% endblock %}-->

{% block javascript %}

<style type="text/css">
  .page-header {
    margin-top: 0;
  }

      .container {
        
        border: 1px ;
        padding: 3px;
      }
      .miniatura {
        display: inline-block;
        border: 1px solid black;
        margin:3px;
      }
      .foto img {
        width: 100px;
        
      }
      .texto {
        padding:5px;
        font-size: 12px;
      }



</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div>
                <img class="img-fluid" src="{% static 'img/logotipo.jpeg' %}">
            </div>
            <div class="text-center">
                <h5>
                    Momentos Imagem
                </h5>
                <h6>
                    Fotografias & Studio Escolar
                </h6>
            </div>
            <div class="p-1 text-left" style="font-size: 11px;">
                <small>Rua Mário Mendes de Lara, 64 - Uberaba - Curitiba - PR<br/>
                    Telefones: 41 99906 9775 - 99703 9902 - </br>
                    41 3376 2049<br/>
                    email: momentosimagem@gmail.com<br/>
                    redes sociais: facebook/momentos2017<br/>
                    website: momentosimagem.com.br<br/>
                </small>
            </div>
        </div>
        <div class="col-md-8"
        ">
        <h2 class="text-center">
            Queridos Responsaveis
        </h2>
        <p>
            A infância é um tempo muito gracioso, cheio de carinho, amor e aprendizado. Pensado nisso, a
            MOMENTOS IMAGENS registra com belas fotos esse período tão lindo.
            Apresentamos as amostras destas fotos para que possam ser escolhidas as fotos de sua preferência.
            Lembrando que podem ser escolhidas quantas fotos quiserem. Não há obrigatoriedade de pedido minimo.
        <h6 class="text-center">
            Anexo a este copião estão as instruções e preços para pedido.
        </h6>
        </p>
    </div>
</div>
<div class="row p-2" style="font-weight: bold; ">
    <div class="col-md-4 text-center">
        Sofia Adral - Infantil - 2C
    </div>
    <div class="col-md-8 text-center">
        CMEI A BAB DO PASSARINHO - S. J. PINHAIS - MAR/2017
    </div>
</div>

<div class="row">
    <div class="col-md-12" style="min-height: 600px; border: 1px solid gray">
        <div class="container">
            {% for photo in photos %}
            <div class="miniatura">
                <div class="foto">
                    {% cloudinary photo.image.name width=100 height=100 %}
                </div>
                <div class="texto">
                    {{ photo.title }}
                </div>
            </div>
            {% endfor %}

        </div>

    </div>
</div>



{% endblock %}

templates/photos/progress_bar_upload/progress.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Carregando Fotos{% endblock %}

{% block content %}
<div class="container">

<div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
    </button>
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'photos:progress_bar_upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>


    <table id="gallery" class="table table-bordered">
        <thead>
        <tr>
            <th>Lista de arquivos de Fotos Carregados</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

    <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Uploading...</h4>
      </div>
      <div class="modal-body">
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}